---
- name: Get device configuration
  hosts:
    - all
  vars:
    username: admin
    backup_dir: "./junos_backup"
    conf_file: "{{ backup_dir }}/{{ inventory_hostname }}.conf"
  connection: local
  gather_facts: no
  tasks:
    - name: create backup directory
      file:
        path: "{{ backup_dir }}"
        state: directory
    - name: get device configuration
      juniper.device.config:
         host: "{{ ansible_host }}"
         user: "{{ username }}"
         dest: "{{ conf_file}}"
         retrieve: committed
         format: text
